version: '2.1'
services:
  rtl_433:
    build: rtl433_docker
    devices:
        - /dev/bus/usb 
    privileged: true
    restart: on-failure
    command: ["-G", "-F", "syslog:${SYSLOG_HOST:-127.0.0.1}:${SYSLOG_PORT:-1514}"]
